---
abstract: 'prepare unicode stream to be encoded as cp1251'
author:
  - 'liosha <liosha@cpan.org>'
build_requires:
  Encode: '0'
  List::MoreUtils: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PerlIO-via-PrepareCP1251
requires:
  Unicode::Normalize: '0'
  charnames: '0'
  perl: '5.010'
  strict: '0'
  utf8: '0'
  warnings: '0'
version: '0.02'
